# Generated by Django 3.2.19 on 2023-05-28 19:18
# Django sees that we've added a new model to our app so it creates a new Python file in the
# migrations folder. That contains the code to create that database table based on our model.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
